[package]
name = "p2p"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
rayon = "1.10.0"
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.140"
sha2 = {version="0.10.8"}
